import { jsPDF } from "jspdf";
import "jspdf-autotable";

/**
 * PDF Export Utilities for RobotCop SOC Dashboard
 * 
 * Provides functions to export:
 * - Forensics reports
 * - Compliance evidence
 * - Incident details
 * - NIST compliance scores
 */

interface ForensicsReportData {
  incidentId: string;
  timestamp: Date;
  narrative: string;
  riskAssessment: {
    severity: string;
    confidenceScore: number;
    dataExposureRisk: string;
    lateralMovementRisk: string;
  };
  recommendations: string[];
}

interface IncidentData {
  id: string;
  timestamp: Date;
  severity: string;
  title: string;
  description: string;
  source: string;
  status: string;
  details?: {
    affectedResources?: string[];
    rootCause?: string;
    detectionMethod?: string;
    remediationSteps?: string[];
    forensicSnapshot?: string;
  };
}

interface ComplianceReportData {
  frameworks: Array<{
    name: string;
    score: number;
    status: string;
    lastAudit: Date;
  }>;
  overallScore: number;
  generatedAt: Date;
}

/**
 * Export forensics report as PDF
 */
export function exportForensicsReportPDF(data: ForensicsReportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(102, 204, 255); // Neon Blue
  doc.text("RobotCop SOC Dashboard", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 10;
  doc.setFontSize(14);
  doc.setTextColor(136, 136, 136); // Muted Gray
  doc.text("Executive Forensics Report", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 15;

  // Incident Information
  doc.setFontSize(11);
  doc.setTextColor(224, 224, 224); // Light Gray
  doc.text(`Incident ID: ${data.incidentId}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Generated: ${data.timestamp.toLocaleString()}`, 20, yPosition);
  yPosition += 12;

  // Risk Assessment
  doc.setFontSize(12);
  doc.setTextColor(102, 204, 255); // Neon Blue
  doc.text("Risk Assessment", 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setTextColor(224, 224, 224);
  const riskAssessmentData = [
    ["Severity", data.riskAssessment.severity],
    ["Confidence Score", `${data.riskAssessment.confidenceScore}%`],
    ["Data Exposure Risk", data.riskAssessment.dataExposureRisk],
    ["Lateral Movement Risk", data.riskAssessment.lateralMovementRisk],
  ];

  (doc as any).autoTable({
    startY: yPosition,
    head: [["Metric", "Value"]],
    body: riskAssessmentData,
    theme: "dark",
    headStyles: {
      fillColor: [102, 204, 255],
      textColor: [18, 18, 30],
      fontStyle: "bold",
    },
    bodyStyles: {
      fillColor: [40, 40, 50],
      textColor: [224, 224, 224],
    },
    margin: { left: 20, right: 20 },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 12;

  // Narrative
  doc.setFontSize(12);
  doc.setTextColor(102, 204, 255);
  doc.text("Forensic Analysis", 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setTextColor(224, 224, 224);
  const splitNarrative = doc.splitTextToSize(data.narrative, pageWidth - 40);
  doc.text(splitNarrative, 20, yPosition);
  yPosition += splitNarrative.length * 5 + 10;

  // Recommendations
  if (data.recommendations.length > 0) {
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(12);
    doc.setTextColor(102, 204, 255);
    doc.text("Recommendations", 20, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setTextColor(224, 224, 224);
    data.recommendations.forEach((rec) => {
      const splitRec = doc.splitTextToSize(`• ${rec}`, pageWidth - 40);
      doc.text(splitRec, 20, yPosition);
      yPosition += splitRec.length * 5 + 3;

      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = 20;
      }
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(136, 136, 136);
  doc.text(
    `Generated by RobotCop AI Analysis Engine • ${new Date().toLocaleString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  doc.save(`forensics-report-${data.incidentId}.pdf`);
}

/**
 * Export incident details as PDF
 */
export function exportIncidentPDF(data: IncidentData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 20;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(102, 204, 255);
  doc.text("Incident Report", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 12;

  // Incident Title
  doc.setFontSize(14);
  doc.setTextColor(224, 224, 224);
  doc.text(data.title, 20, yPosition);

  yPosition += 10;

  // Incident Details
  doc.setFontSize(10);
  doc.setTextColor(224, 224, 224);
  const incidentDetails = [
    ["Incident ID", data.id],
    ["Severity", data.severity.toUpperCase()],
    ["Detection Time", data.timestamp.toLocaleString()],
    ["Source", data.source],
    ["Status", data.status],
  ];

  (doc as any).autoTable({
    startY: yPosition,
    head: [["Field", "Value"]],
    body: incidentDetails,
    theme: "dark",
    headStyles: {
      fillColor: [102, 204, 255],
      textColor: [18, 18, 30],
      fontStyle: "bold",
    },
    bodyStyles: {
      fillColor: [40, 40, 50],
      textColor: [224, 224, 224],
    },
    margin: { left: 20, right: 20 },
  });

  yPosition = (doc as any).lastAutoTable.finalY + 12;

  // Description
  doc.setFontSize(11);
  doc.setTextColor(102, 204, 255);
  doc.text("Description", 20, yPosition);
  yPosition += 7;

  doc.setFontSize(10);
  doc.setTextColor(224, 224, 224);
  const splitDesc = doc.splitTextToSize(data.description, pageWidth - 40);
  doc.text(splitDesc, 20, yPosition);
  yPosition += splitDesc.length * 5 + 10;

  // Additional Details
  if (data.details) {
    if (data.details.affectedResources && data.details.affectedResources.length > 0) {
      doc.setFontSize(11);
      doc.setTextColor(102, 204, 255);
      doc.text("Affected Resources", 20, yPosition);
      yPosition += 7;

      doc.setFontSize(10);
      doc.setTextColor(224, 224, 224);
      data.details.affectedResources.forEach((resource) => {
        doc.text(`• ${resource}`, 25, yPosition);
        yPosition += 5;
      });
      yPosition += 5;
    }

    if (data.details.remediationSteps && data.details.remediationSteps.length > 0) {
      doc.setFontSize(11);
      doc.setTextColor(102, 204, 255);
      doc.text("Remediation Steps", 20, yPosition);
      yPosition += 7;

      doc.setFontSize(10);
      doc.setTextColor(224, 224, 224);
      data.details.remediationSteps.forEach((step, index) => {
        doc.text(`${index + 1}. ${step}`, 25, yPosition);
        yPosition += 5;
      });
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(136, 136, 136);
  doc.text(
    `RobotCop SOC Dashboard • ${new Date().toLocaleString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  doc.save(`incident-report-${data.id}.pdf`);
}

/**
 * Export compliance report as PDF
 */
export function exportComplianceReportPDF(data: ComplianceReportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 20;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(102, 204, 255);
  doc.text("Compliance Report", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 12;

  // Overall Score
  doc.setFontSize(12);
  doc.setTextColor(102, 204, 255);
  doc.text("Overall Compliance Score", 20, yPosition);
  yPosition += 8;

  doc.setFontSize(28);
  doc.setTextColor(102, 204, 255);
  doc.text(`${data.overallScore}%`, 20, yPosition);
  yPosition += 20;

  // Framework Scores
  doc.setFontSize(12);
  doc.setTextColor(102, 204, 255);
  doc.text("Framework Compliance", 20, yPosition);
  yPosition += 8;

  const frameworkData = data.frameworks.map((f) => [
    f.name,
    `${f.score}%`,
    f.status,
    f.lastAudit.toLocaleDateString(),
  ]);

  (doc as any).autoTable({
    startY: yPosition,
    head: [["Framework", "Score", "Status", "Last Audit"]],
    body: frameworkData,
    theme: "dark",
    headStyles: {
      fillColor: [102, 204, 255],
      textColor: [18, 18, 30],
      fontStyle: "bold",
    },
    bodyStyles: {
      fillColor: [40, 40, 50],
      textColor: [224, 224, 224],
    },
    margin: { left: 20, right: 20 },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(136, 136, 136);
  doc.text(
    `Generated: ${data.generatedAt.toLocaleString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" }
  );

  doc.save(`compliance-report-${data.generatedAt.getTime()}.pdf`);
}
