import { useMemo } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Brain, AlertTriangle, CheckCircle2, Lightbulb, TrendingUp } from "lucide-react";
import {
  mockForensicsReport,
  mockRootCauseAnalysis,
} from "@/lib/mockData";

/**
 * Cognitive AI Insights Page - "The Wisdom"
 * 
 * Design: Dark SOC aesthetic with AI/cognitive focus
 * - Executive Forensics Reports: AI-generated narrative analysis
 * - Automated Root Cause Analysis: Why incidents happen
 * - Prevention Strategies: Actionable recommendations
 */

export default function Insights() {
  const forensicsReport = useMemo(() => {
    return mockForensicsReport;
  }, []);

  const rootCauseAnalysis = useMemo(() => {
    return mockRootCauseAnalysis;
  }, []);

  const getRiskColor = (risk: string) => {
    switch (risk.toUpperCase()) {
      case "LOW":
        return "text-neon-green";
      case "MEDIUM":
        return "text-orange-warning";
      case "HIGH":
        return "text-neon-red";
      case "CRITICAL":
        return "text-neon-red";
      default:
        return "text-cyan-accent";
    }
  };

  return (
    <div className="space-y-8">
      {/* Page Header */}
      <div className="space-y-2">
        <h1 className="text-4xl font-bold text-foreground font-mono">
          The Wisdom
        </h1>
        <p className="text-muted-foreground">
          Cognitive analysis powered by Amazon Bedrock (Claude 3 Sonnet)
        </p>
      </div>

      {/* Executive Forensics Report */}
      <Card className="bg-card border-border p-8 glow-blue">
        <div className="space-y-6">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-lg font-bold text-foreground font-mono mb-2">
                Executive Forensics Report
              </h2>
              <p className="text-sm text-muted-foreground font-mono">
                Incident ID: {forensicsReport.incidentId}
              </p>
            </div>
            <Badge className="bg-neon-blue/20 text-neon-blue border-neon-blue/50">
              <Brain className="w-3 h-3 mr-1" />
              AI-Generated
            </Badge>
          </div>

          {/* Narrative Report */}
          <div className="bg-secondary rounded-lg p-6 border border-border space-y-4">
            <p className="text-sm leading-relaxed text-foreground">
              {forensicsReport.narrative}
            </p>
            <div className="text-xs text-muted-foreground font-mono border-t border-border pt-4">
              Generated by {forensicsReport.generatedBy} at{" "}
              {forensicsReport.timestamp.toLocaleString()}
            </div>
          </div>

          {/* Risk Assessment */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-secondary rounded-lg p-4 border border-border">
              <p className="text-xs text-muted-foreground font-mono mb-2">Severity</p>
              <p className={`text-lg font-bold font-mono ${getRiskColor(forensicsReport.riskAssessment.severity)}`}>
                {forensicsReport.riskAssessment.severity}
              </p>
            </div>
            <div className="bg-secondary rounded-lg p-4 border border-border">
              <p className="text-xs text-muted-foreground font-mono mb-2">Confidence</p>
              <p className="text-lg font-bold text-neon-blue font-mono">
                {forensicsReport.riskAssessment.confidenceScore}%
              </p>
            </div>
            <div className="bg-secondary rounded-lg p-4 border border-border">
              <p className="text-xs text-muted-foreground font-mono mb-2">Data Exposure</p>
              <p className={`text-lg font-bold font-mono ${getRiskColor(forensicsReport.riskAssessment.dataExposureRisk)}`}>
                {forensicsReport.riskAssessment.dataExposureRisk}
              </p>
            </div>
            <div className="bg-secondary rounded-lg p-4 border border-border">
              <p className="text-xs text-muted-foreground font-mono mb-2">Lateral Movement</p>
              <p className={`text-lg font-bold font-mono ${getRiskColor(forensicsReport.riskAssessment.lateralMovementRisk)}`}>
                {forensicsReport.riskAssessment.lateralMovementRisk}
              </p>
            </div>
          </div>

          {/* Recommendations */}
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-foreground font-mono">
              AI-Generated Recommendations
            </h3>
            {forensicsReport.recommendations.map((rec, index) => (
              <div
                key={index}
                className="flex gap-3 p-4 bg-secondary rounded-lg border border-border hover:border-neon-blue/50 transition-colors"
              >
                <Lightbulb className="w-5 h-5 text-neon-blue flex-shrink-0 mt-0.5" />
                <p className="text-sm text-foreground">{rec}</p>
              </div>
            ))}
          </div>
        </div>
      </Card>

      {/* Root Cause Analysis */}
      <Card className="bg-card border-border p-8">
        <div className="space-y-6">
          <h2 className="text-lg font-bold text-foreground font-mono">
            Automated Root Cause Analysis
          </h2>

          {/* Root Causes */}
          <div className="space-y-4">
            {rootCauseAnalysis.rootCauses.map((cause, index) => (
              <div
                key={index}
                className="bg-secondary rounded-lg p-6 border border-border space-y-3"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <h3 className="text-sm font-bold text-foreground font-mono mb-2">
                      {cause.cause}
                    </h3>
                    <p className="text-sm text-muted-foreground mb-3">
                      {cause.evidence}
                    </p>
                    <div className="flex items-center gap-2">
                      <span className="text-xs text-muted-foreground font-mono">
                        Probability:
                      </span>
                      <div className="flex-1 max-w-xs h-2 bg-muted rounded-full overflow-hidden">
                        <div
                          className="h-full bg-gradient-to-r from-neon-blue to-neon-green"
                          style={{ width: `${cause.probability}%` }}
                        />
                      </div>
                      <span className="text-sm font-bold text-neon-blue font-mono">
                        {cause.probability}%
                      </span>
                    </div>
                  </div>
                </div>

                {/* Mitigation */}
                <div className="border-t border-border pt-3">
                  <div className="flex items-start gap-2">
                    <CheckCircle2 className="w-4 h-4 text-neon-green flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs text-muted-foreground font-mono mb-1">
                        Mitigation Strategy
                      </p>
                      <p className="text-sm text-foreground">{cause.mitigation}</p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Prevention Strategies */}
          <div className="space-y-3 pt-6 border-t border-border">
            <h3 className="text-sm font-bold text-foreground font-mono">
              Long-Term Prevention Strategies
            </h3>
            {rootCauseAnalysis.preventionStrategies.map((strategy, index) => (
              <div
                key={index}
                className="flex gap-3 p-4 bg-secondary rounded-lg border border-border hover:border-neon-green/50 transition-colors"
              >
                <TrendingUp className="w-5 h-5 text-neon-green flex-shrink-0 mt-0.5" />
                <p className="text-sm text-foreground">{strategy}</p>
              </div>
            ))}
          </div>
        </div>
      </Card>

      {/* AI Insights Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="bg-card border-border p-6 glow-blue">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Brain className="w-5 h-5 text-neon-blue" />
              <p className="text-xs text-muted-foreground font-mono">
                AI Analysis Quality
              </p>
            </div>
            <p className="text-3xl font-bold text-neon-blue font-mono">98.7%</p>
            <p className="text-xs text-muted-foreground mt-2 font-mono">
              Confidence score for this analysis
            </p>
          </div>
        </Card>

        <Card className="bg-card border-border p-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-orange-warning" />
              <p className="text-xs text-muted-foreground font-mono">
                Root Causes Identified
              </p>
            </div>
            <p className="text-3xl font-bold text-orange-warning font-mono">
              {rootCauseAnalysis.rootCauses.length}
            </p>
            <p className="text-xs text-muted-foreground mt-2 font-mono">
              Primary and contributing factors
            </p>
          </div>
        </Card>

        <Card className="bg-card border-border p-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-neon-green" />
              <p className="text-xs text-muted-foreground font-mono">
                Recommendations
              </p>
            </div>
            <p className="text-3xl font-bold text-neon-green font-mono">
              {forensicsReport.recommendations.length +
                rootCauseAnalysis.preventionStrategies.length}
            </p>
            <p className="text-xs text-muted-foreground mt-2 font-mono">
              Actionable next steps
            </p>
          </div>
        </Card>
      </div>

      {/* AI Model Information */}
      <Card className="bg-secondary border-border p-6">
        <div className="space-y-4">
          <h3 className="text-sm font-bold text-foreground font-mono">
            AI Model & Analysis Details
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-xs text-muted-foreground font-mono mb-1">
                Model
              </p>
              <p className="text-sm text-foreground font-mono">
                Claude 3 Sonnet
              </p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground font-mono mb-1">
                Provider
              </p>
              <p className="text-sm text-foreground font-mono">
                Amazon Bedrock
              </p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground font-mono mb-1">
                Analysis Type
              </p>
              <p className="text-sm text-foreground font-mono">
                Multi-factor RCA
              </p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground font-mono mb-1">
                Processing Time
              </p>
              <p className="text-sm text-foreground font-mono">
                8.2 seconds
              </p>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
